version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
  app:
    container_name: yuvelirny_ukrasheniy
    build: 
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - ${API_LOCAL_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - API_HOST=${API_HOST}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_LOCAL_PORT=${DB_LOCAL_PORT}
      - DB_HOST=postgres